dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: gUvQwvKPirUVTnvyg8EJqWYBwCRpTGUOGwP28HZsQZEgeq6g7CWjKTt8d4jtX+sYtYym/St2tivDMq80GI6kAfGkXK85LWLEFW1+biEfZOHPbglsEpC0H9Z8NWNiO18yiHaayOvwj5nxj/8TP6LRO3v0B0sttWrulGYcfK4sP2nb1Ajb9CTT5yb9RSRXj4zFipuFZ/5in4+JJegxHbs12ZbQF2ivkzyoUsOglg/L6PAZjaF+Lvbth2EV2J8iMdmjsU715HWyhKB7FKeBIIWPvWOTV0TRFS4DfjJsK7iKVCzuLZv+szkuXGkxgh/n650yCQ7PwfJxR1jus2hzzC6/XoiJi0BAODy0A4kfwdkNFOyNNZ5H3EaV5KUPtBbnBMTovGcr2aLTLSLXS5PlDA2IOgR86v18Ob5KpUVmmcHlYd7p6et7gnBN/lNQ36gBnsULV6vqG71Cm8SQ/Hz1cjV+i8LDM+rJNRSj9bcy4kmn6lzgs1GSeNiWw+sWWNQzd2WqEWHwCXnZtXhU09rVfMe948wvpqSG/C0Yz4SnN/2deFgAn/gssjgIY78GoMq8hVzysuPsNX9iLsI3SNZ7emw0YSbsI6LhY+LAOibK6EqXgWYEFR+AaDaav3KukXV6lOUW3NoLFwEKdj4nzr27UHD9h0NVJDc5jHeWKpZ+1pMp37A=
  - secure: vTFK/Fft70nQNLMZzldkub1E3vYFKMqYM7Sp9Opt8VVDB2RdaDFKWaES8jUotywVscMUzpDDdaAx3b+4qBPc3Kj4JEBCvq9adpix7eDi9ZEfzjuS96FySSsGg3ThNiahMAhTeOfGnHS1R7PsKO13WjElXTJkkPvBmgFRTyIuEvpTLS1rmVPHdrhbWEOhBDsfBkj8WDLmvQqnSydqy8LBe+lFDfqQrfAf3dKqhcqj+k+/WqI0gJmbajAs9C1r+5atIo0922xU22uc2o6lxM3wKA7dT6iZY3JiV8ixRs8rk/vwegGLkLMjHJ48caUiLKTw3FTg4ptFpVQVv2DUEYIbTn9vrW4ClXmep7RetghsD6qg9++8W6lKelhkzP3y6F9DWK2OKW8fFqwNvylbrCaJrNw68bandhME7ReHli0U3dxWZ/WaYLIH37vm2HR29FVoRCFOZ913iRPEv+4FLUxKsjcKRX36gQFwL0htAkutRkxGJHdKyZLgtvBo8FPp05dEuMUrMAC6stDvJxkS4s8CJli1wllhNHLGxzVk7+I/zD4+qG906Zu74pmxZLkYIHS9w/UW8dVfyYz56I8RVloQ/tEmc5QAtsHnDXXr+2JjFyc9r8sQ8SbCLrYSeFxeF1P0SeLfYeOwgvvjjFHhUhdNwqmEIpgTiS+ybVtM/cFi67M=
  - secure: owTiNPCoMI8Lp8oM3UOuc7F7cE8ow0LEPKA+txDRTuvPhPypHMNCQvtLlbrk+Pt2f3D1tpCWjkxAnRXl/UDbTCXtskMPqqTEe3L+uNouruKdL7W+nOXuMhvkZLUCSVv3U1J7uTsBme1E2kBwRyhe83dasHfZGf+CS+LUGyUvtbfdEocQwVVd80Nt6oN91l3GT0O+s7SfLH7DGq6y7INpgGqLDSpoqUKp44Ubshkq6LQcFroLaxU7VYVnlQN+tp3Vsb9ezzTAO5TfnKO0aa6U3w8PYDyISZrZAT+LPTU6XJ7AycrPqacUMVpRAd31KWlfJqdwW+Mgnwi5vL92fEGg8bMRw763kS/Ym5fy0JPGYn/Y6v7nBfHhRrg1h3bLqak5wIhkDNPxMRON+pRXWkYM8zNDsX4BGNW+7LuEoiHCxPUvSzRYDvkDb0qHBlZzOohhspqHA9ihpa0DFQScIPIBVC02DTcLSoe79UMur3QhCmeD2PU1izG4NQkhurGKkoalq9Ukv0QlrKUwY/jUi7PycuHTZ8e50shUEuTCkLGAvWDDValqr7cnKsJqJCqskzd3iJwc3bud0VCF8/NpSo7gfwpPlQsB09TLWZ5vyf382lw9PNUxJ5Ft5Gf7llc2eVKlcvg1qHQ7y46uA5n6RO1svNF4bKhUSwOtjRtq1PjQ0XQ=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
